[package]
name = "rust"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-client = "2.2.7"
solana-sdk = "2.2.2"
spl-token-client = "0.14.0"
spl-token-2022 = "8.0.1"
spl-associated-token-account = "6.0.0"

anyhow = "1.0.98"
dotenvy = "0.15.7"
serde_json = "1.0.140"
