[package]
name = "rust"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-client = "2.1.12"
solana-sdk = "2.1.12"
spl-token-client = "0.14.0"
spl-token-2022 = "7.0.0"
spl-associated-token-account = "6.0.0"

anyhow = "1.0.95"
dotenv = "0.15.0"
serde_json = "1.0.138"
